@echo off
chcp 65001 >nul
cd /d "%~dp0"
echo Initializing git repository...
if not exist .git git init
echo Adding remote...
git remote remove origin 2>nul
git remote add origin https://github.com/Nikkfh5/final_project.git
echo Adding files...
git add .
echo Committing...
git commit -m "Add project structure: Gazebo simulation package and Python tracker package"
echo Setting branch to main...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
pause

